### ISSUE TITLE
Something with offset due to parallax

### ISSUE THREAD

**Issue by subdavis** [HackNC/fall2016#3]
![13418488_10209197857610739_8585827914609929946_o](https://cloud.githubusercontent.com/assets/4214172/15986110/9ccf2c8c-2fcd-11e6-93c6-a1133eb50d1f.jpg)

Found by Adam

**Comment by adamaji** [comment]
platform chrome v51 and osx yosemite

**Comment by subdavis** [comment]
issue fixed with tape.
